#!/bin/bash -l

echo "Loading modules for CESM_postprocessing tool..."

module purge
ml NCL/6.6.2-foss-2018b
ml NCO/4.7.9-foss-2018b
ml netCDF/4.6.1-foss-2018b-cdf5
#ml python/2.7.13-generic
ml Python/2.7.15-foss-2018b


source [YOUR-CESM-PP-DIR]/cesm-env2/bin/activate
export PYTHONPATH=[YOUR-CESM-PP-DIR]/pynio/site-packages:$PYTHONPATH
export PYTHONPATH=[YOUR-CESM-PP-DIR]/pynio/build/lib.linux-x86_64-2.7/PyNIO:$PYTHONPATH
export PYNIOPATH=[YOUR-CESM-PP-DIR]/pynio/site-packages/PyNIO


